name: Issue Labeler

on:
  issues:
    types: [opened, edited]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install Dependencies
      run: |
        npm install
        npm install compromise lodash
    - name: Run labeler
      env:
        repo-token: ${{ secrets.GITHUB_TOKEN }}  # use the name of your secret here
      run: node .github/scripts/labeler.js $repo-token ${{ secrets.PAT_ISSUE_LABELER }}